### ISSUE TITLE
verify Subscriptions - sometimes works, sometimes get Error: The project id used to call the Google Play Developer API has not been linked in the Google Play Developer Console.

### ISSUE THREAD

**Issue by Jeffreyoboe1** [Deishelon/google-play-billing-validator#1]
So, this only happens sometimes.  Sometimes, I get a response, and the purchase was validated, sometimes, it does not validate, and I get this error:

Error: The project id used to call the Google Play Developer API has not been linked in the Google Play Developer Console.

Is there some sort of expiration date?  I don't know why I only get this error some of the time, when I am in testing.  Thanks!

**Comment by Deishelon** [comment]
Hi! This might happen if you didn't not connected your Google Cloud project to the Play Console. Please for a look at my very detailed instructions (with screenshots) on medium - https://medium.com/androidhub/how-to-validate-in-app-purchase-subscription-on-your-node-js-backend-a2b823470034

Let me know if you still face this issue.
PS. I use this solution in production, no problems at all :)

**Comment by Jeffreyoboe1** [comment]
Thanks, yes I followed that tutorial, actually.  Like I said, sometimes I have no problems at all, (which means it is connected), and other times, I do have problem and get the above error.  For example, if I quickly subscribe, then cancel the subscription, I get the projected id error.  Any other ideas?  Thank you!

**Comment by Jeffreyoboe1** [comment]
I'm wondering if maybe Google can't handle that many calls for access in quick succession on the same purchase token?

**Comment by Deishelon** [comment]
That's so weird. It shouldn't be the limit issue. You can check your usage on Google APIs page (under Quotas)

I've done a quick google search (I'm sure you have done it too, but anyway)
https://github.com/fastlane/fastlane/issues/12698
https://stackoverflow.com/questions/25481207/why-getting-error-the-project-id-used-to-call-the-google-play-developer-api-has
https://stackoverflow.com/questions/28770283/in-google-api-v2-why-is-the-error-the-project-id-used-to-call-the-google-play

All the answers suggest it's 'linking' issue.

I also tested the same thing (sub, unsub) and I do not see any problems... I will have a look more what could go wrong, but so far no ideas lol, sorry :)

**Comment by Jeffreyoboe1** [comment]
Yeah, I tested this with a second library, similar to yours, and received similar results with their library.  I'm thinking about implementing some sort of retry policy... if I get that error, to then retry for 5-10 times to see if it comes back with the response.  Really don't understand what is causing it yet.

**Comment by Jeffreyoboe1** [comment]
FYI, this is with subscriptions.  Have not tried this for in-app purchases that are not subscriptions.

**Comment by lfreneda** [comment]
@Jeffreyoboe1 same issue here, did you solve it?
