### ISSUE TITLE
Typescript Support

### ISSUE THREAD

**Issue by YogiBear52** [Deishelon/google-play-billing-validator#10]
### Description

Typescript Support.
Add d.ts to project.

**Comment by YogiBear52** [comment]
I have already implemented it but I don't have permissions to Push and open a Pull Request.

**Comment by Deishelon** [comment]
Hi, that'd be an awesome addition. Can you fork the project, and then open PR. Alternatively, you can post the file here and I will merge it manually. Thanks ;)

**Comment by Deishelon** [comment]
Closing the issue, version `2.1.0` with TypeScript support is released
