### ISSUE TITLE
Uncaught SyntaxError: Unexpected token N in JSON at position 0

### ISSUE THREAD

**Issue by sagimann** [Deishelon/google-play-billing-validator#4]
### Description

When calling verifySub with an invalid token, google returns 404 error, but the verify function which calls request() does not receive any error in the response callback - only a 404 return code and a "Not Found" text in the body parameter. This, in turn, causes the exception because "Not Found" is not a valid JSON

### Steps to Reproduce

1. Perform verifySub using a valid package ID and product ID, but an empty string as token
2. Observe the call issues the above error

### Sample code

`
opts = { email:"xxx", key:"yyy" };
const GooglePurchaseVerifier = require('google-play-billing-validator');
verifier = new GooglePurchaseVerifier(opts);
receipt = {
                packageName: "pppp",
                productId: "product1ppppp",
                purchaseToken: ""
            };
verifier.verifySub(receipt);
`

### Expected behavior: 
The verifySub method should fail gracefully

### Actual behavior:
The verifySub throws an uncaught exception

### Versions

node 8.1.0
npm 6.1.0
google-play-billing-validator: 2.0.2

**Comment by Deishelon** [comment]
Hi, thanks for reporting this bug, will fix it & update this thread. Thanks!

**Comment by sagimann** [comment]
Thanks! I would suggest checking the return code prior to parsing the JSON, that's all :)

**Comment by Deishelon** [comment]
Hey, issue fixed, thanks for the heads-up. `2.0.3` is out
