### ISSUE TITLE
Is it possible to add acknowledge method in this module?

### ISSUE THREAD

**Issue by hvaddi9** [Deishelon/google-play-billing-validator#7]
### Description

Current module is just giving the details of the purchase.
Is it possible to add acknowledge method in this module?

### Link
[acknowledge method is mentioned in this link](https://developers.google.com/android-publisher/api-ref/purchases/products/acknowledge)

### Expected behavior: 
acknowledge function to acknowledge the purchase on the server-side

**Comment by Deishelon** [comment]
Sure, will add it 👍

**Comment by hvaddi9** [comment]
I've forked and modified the **verifyInApp** function to support the **acknowledge** method. Making it a generic option and will do a PR. Is it fine?

**Comment by Deishelon** [comment]
Oh wow! That is amazing! I was just about to do it. Yes just submit it 👍

**Comment by Deishelon** [comment]
@hvaddi9 PR is merged & documentation updated. updated pushed to npm, version `2.0.4`

**Comment by hvaddi9** [comment]
@Deishelon  Cool! Happy to contribute :) 
Closing the issue.

**Comment by sandesh-bhoir** [comment]
Its not working @hvaddi9 

```
{
  isSuccessful: false,
  errorCode: 400,
  errorMessage: "Invalid response, please check 'Verifier' configuration or the statusCode above"
}
```
